### ISSUE TITLE
opus file extension

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#295]
I've just been building commons from the dumps and have noticed in the session log a number of lines like:

    20181130_131552.147 image.ext_calc.mismatch_exts: file=20180323-Munich-HBF.opus mime=ogg

That is, the `image.ext_calc.mismatch_exts` error/warning/info message appears for all files with the `opus` extension. 
Wikipedia itself says that 

> Opus was originally specified for encapsulation in Ogg containers, specified as `audio/ogg; codecs=opus`

It now seems to have its own mime type of `audio/opus`. Although I don't know how widespread this is.

I would suggest that this should not generate a message as it is a valid extension

**Comment by gnosygnu** [comment]
Thanks for the heads up. I think this is a rather simple change which I can add in the next few days. It basically consists of adding corresponding entries to : https://github.com/gnosygnu/xowa/blob/master/400_xowa/src/gplx/xowa/files/Xof_ext_.java

I'll push a commit sometime this week. Thanks.

**Comment by gnosygnu** [comment]
I pushed the change now. I don't have a way to test this easily, but usually this is just a matter of registering a new file type.

Thanks again for the report

**Comment by desb42** [comment]
I have just rebuilt commons from the 2019-01-01 dump with the changes that you mentioned and I still get the error.
I believe this is due to the need to amend Xobldr__image__create.java also
lines 97-98

    case Xof_ext_.Id_ogg: case Xof_ext_.Id_oga: case Xof_ext_.Id_ogv:
        if (Int_.In(mime_ext_id, Xof_ext_.Id_ogg, Xof_ext_.Id_oga, Xof_ext_.Id_ogv)) notify = false;	// skip: both tif
I think should now take opus into account eg

    case Xof_ext_.Id_ogg: case Xof_ext_.Id_oga: case Xof_ext_.Id_ogv: case Xof_ext_.Id_opus:
        if (Int_.In(mime_ext_id, Xof_ext_.Id_ogg, Xof_ext_.Id_oga, Xof_ext_.Id_ogv, Xof_ext_.Id_opus)) notify = false;	// skip: both tif

What do you think?
